# Generated by Django 5.2.7 on 2025-10-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=120)),
                ('temporada', models.CharField(choices=[('INV', 'Invierno'), ('OTÑ', 'Otoño'), ('PRI', 'Primavera'), ('VER', 'Verano')], max_length=60)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('marca', models.CharField(max_length=60)),
            ],
        ),
    ]
