# Generated by Django 5.2.7 on 2025-10-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('U', 'Unisex')], max_length=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='temporada',
            field=models.CharField(choices=[('INV', 'Invierno'), ('OTÑ', 'Otoño'), ('PRI', 'Primavera'), ('VER', 'Verano'), ('ALL', 'all')], max_length=60),
        ),
    ]
