# Generated by Django 5.2.7 on 2025-11-09 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto_variante', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_cliente', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion_cliente', models.TextField(blank=True, null=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_vendedor', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('tipo_venta', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], max_length=20)),
                ('plazo_meses', models.PositiveIntegerField(blank=True, null=True)),
                ('interes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_con_interes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuota_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(blank=True, limit_choices_to={'rol': 'cliente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_como_cliente', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(limit_choices_to={'rol': 'vendedor'}, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_como_vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('talla', models.CharField(blank=True, max_length=10, null=True)),
                ('variante_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto_variante.varianteproducto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='venta.venta')),
            ],
        ),
    ]
