# Generated by Django 5.2.7 on 2025-10-30 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto_variante', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total sin interés', max_digits=10)),
                ('tipo_pago', models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=10)),
                ('interes', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de interés (ej: 15.00 = 15%)', max_digits=5, null=True)),
                ('total_con_interes', models.DecimalField(blank=True, decimal_places=2, help_text='Total con interés aplicado', max_digits=10, null=True)),
                ('plazo_meses', models.IntegerField(blank=True, help_text='Número de meses para pagar', null=True)),
                ('cuota_mensual', models.DecimalField(blank=True, decimal_places=2, help_text='Monto de cada cuota mensual', max_digits=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio al momento de la venta', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='cantidad * precio_unitario', max_digits=10)),
                ('producto_nombre', models.CharField(max_length=60)),
                ('talla', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=30)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='producto_variante.varianteproducto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='venta.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['-fecha'], name='venta_venta_fecha_4168b4_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['cliente', 'estado_pago'], name='venta_venta_cliente_20b510_idx'),
        ),
    ]
