# Generated by Django 5.2.7 on 2025-11-09 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_venta_cuota_mensual_alter_venta_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='origen',
            field=models.CharField(choices=[('tienda', 'Tienda Física'), ('ecommerce', 'Ecommerce')], default='tienda', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='nombre_vendedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'vendedor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_como_vendedor', to=settings.AUTH_USER_MODEL),
        ),
    ]
