# Generated by Django 5.2.7 on 2025-11-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_venta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='talla',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
