# Generated by Django 5.2.7 on 2025-11-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_variante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varianteproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='variantes/'),
        ),
    ]
