# Generated by Django 5.2.7 on 2025-11-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_variante', '0001_initial'),
        ('productos', '0006_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varianteproducto',
            options={'verbose_name': 'Variante de Producto', 'verbose_name_plural': 'Variantes de Productos'},
        ),
        migrations.AlterField(
            model_name='varianteproducto',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='varianteproducto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='varianteproducto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='varianteproducto',
            name='talla',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='varianteproducto',
            unique_together={('producto', 'talla', 'color')},
        ),
    ]
