# Generated by Django 5.2.7 on 2025-11-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto_variante', '0002_alter_varianteproducto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varianteproducto',
            name='imagen',
        ),
    ]
