# Generated by Django 5.2.7 on 2025-11-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('ADMIN', 'Administrador'), ('EMPLEADO', 'Empleado')], default='CLIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
