# Generated by Django 5.2.7 on 2025-11-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('vendedor', 'Vendedor'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
    ]
