# Generated by Django 5.2.7 on 2025-11-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Token FCM para notificaciones push', max_length=255, null=True),
        ),
    ]
