# Generated by Django 5.2.7 on 2025-10-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField(help_text='Número de cuota (1, 2, 3...)')),
                ('fecha_vencimiento', models.DateField()),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], default='pendiente', max_length=10)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cuota de Crédito',
                'verbose_name_plural': 'Cuotas de Crédito',
                'ordering': ['venta', 'numero_cuota'],
            },
        ),
    ]
