# Generated by Django 5.2.7 on 2025-10-30 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuota', '0001_initial'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotacredito',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='venta.venta'),
        ),
        migrations.AlterUniqueTogether(
            name='cuotacredito',
            unique_together={('venta', 'numero_cuota')},
        ),
    ]
