# Generated by Django 5.2.7 on 2025-11-11 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaAnomalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta_baja', 'Venta inusualmente baja'), ('venta_alta', 'Venta inusualmente alta'), ('producto_anomalo', 'Producto con comportamiento anómalo'), ('tendencia_negativa', 'Tendencia negativa detectada')], max_length=50)),
                ('fecha_deteccion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_referencia', models.DateField(help_text='Fecha de la venta anómala')),
                ('descripcion', models.TextField()),
                ('score_anomalia', models.FloatField(help_text='Score de anomalía (-1 = anomalía, 1 = normal)')),
                ('producto_id', models.IntegerField(blank=True, null=True)),
                ('producto_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('valor_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('revisada', 'Revisada'), ('resuelta', 'Resuelta'), ('ignorada', 'Ignorada')], default='nueva', max_length=20)),
                ('nota_resolucion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alerta de Anomalía',
                'verbose_name_plural': 'Alertas de Anomalías',
                'ordering': ['-fecha_deteccion'],
            },
        ),
        migrations.CreateModel(
            name='ModeloEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='modelo_ventas', max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('fecha_entrenamiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('mae', models.FloatField(blank=True, help_text='Mean Absolute Error', null=True)),
                ('mse', models.FloatField(blank=True, help_text='Mean Squared Error', null=True)),
                ('r2_score', models.FloatField(blank=True, help_text='R² Score', null=True)),
                ('registros_entrenamiento', models.IntegerField(default=0)),
                ('registros_prueba', models.IntegerField(default=0)),
                ('archivo_modelo', models.CharField(help_text='Ruta del archivo .pkl', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Modelo de Entrenamiento',
                'verbose_name_plural': 'Modelos de Entrenamiento',
                'ordering': ['-fecha_entrenamiento'],
            },
        ),
    ]
