# Generated by Django 5.2.7 on 2025-11-09 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('qr', 'QR')], max_length=50)),
                ('referencia_pago', models.CharField(blank=True, help_text='Número de transacción, voucher, etc.', max_length=100, null=True)),
                ('cuota', models.ForeignKey(blank=True, help_text='Cuota específica que se está pagando (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='cuota.cuotacredito')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
