# Generated by Django 5.2.7 on 2025-11-09 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pago', '0001_initial'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='venta.venta'),
        ),
    ]
