# Generated by Django 5.2.7 on 2025-11-03 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuota', '0002_initial'),
        ('pago', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cuota',
            field=models.ForeignKey(blank=True, help_text='Cuota específica que se está pagando (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='cuota.cuotacredito'),
        ),
    ]
